---
language: python
python: "2.7"
sudo: true

addons:
  apt:
    packages:
    - ansible
    
# before_install:
#   - sudo apt-get install software-properties-common -y
#   - sudo add-apt-repository ppa:ansible/ansible -y
#   - sudo apt-get update -q
  
before_script:
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory -c local -vvv
  # - >
    # ansible-playbook tests/test.yml -i tests/inventory -c local
    # | grep -q 'changed=0.*failed=0'
    # && (echo 'Idempotence test: pass' && exit 0)
    # || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
