--- 
# - name: setup 
  # command: command -v nvim
  # register: nvim_install_check

- block:
    - name: setup
      file: path={{ neovim_release.install_dir | dirname }} state=directory
    # TODO: figure out a way to install a OS X binary as well...
    # FIXME: nvim cannot find it's share directory when installing this way
    # (plugins etc.) expect it to be /share/
    - name: unarchive | neovim release
      unarchive: src={{ neovim_release.url }} dest={{ neovim_release.install_dir | dirname }} copy=no creates={{ neovim_release.install_dir }}/bin/nvim
  # when: nvim_install_check.rc != 0
  tags: 
    - bootstrap
    - install
    - update

- block:
    - name: bash/zsh | configure | $PATH
      blockinfile:
        dest: "{{ neovim_shell_config_file }}"
        create: yes
        backup: no
        state: "{{ neovim_config_state }}"
        marker: "{{ neovim_marker }}"
        block: |
          if [[ ! "$PATH" == *"{{ neovim_release.install_dir }}/bin"* ]]; then
            export PATH="$PATH:{{ neovim_release.install_dir }}/bin"
          fi
      when: ansible_user_shell | match(".*\/(bash|zsh)")

    - name: fish | configure | $PATH
      command: fish -c "echo $fish_user_paths | grep {{ neovim_data_dir }}/bin > /dev/null; or set -Ux fish_user_paths $fish_user_paths {{ neovim_data_dir }}/bin"
      when: ansible_user_shell | match(".*\/fish")
  tags:
    - bootstrap
    - configure
